import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Refund Policy | ABCV',
  description: 'Refund Policy for ABCV - the AI-powered CV generator.',
};

export default function RefundPolicy() {
  return (
    <div className="min-h-screen bg-background py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-card rounded-xl shadow-sm border border-border/60 p-8 sm:p-12">
        <div className="mb-8 border-b border-border/60 pb-8">
          <Link href="/" className="text-primary hover:text-primary/80 font-medium flex items-center mb-6">
            &larr; Back to Home
          </Link>
          <h1 className="text-3xl font-extrabold text-foreground sm:text-4xl">Refund Policy</h1>
          <p className="mt-2 text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <div className="max-w-none text-foreground space-y-6">
          <p className="leading-relaxed">
            Thank you for choosing ABCV. We strive to provide the best AI-powered CV generation service. Please read this policy carefully as it dictates the conditions under which refunds are provided.
          </p>

          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">1. Digital Goods</h2>
          <p className="leading-relaxed">
            Due to the nature of digital goods and services provided by ABCV (AI-generated CVs and cover letters), all sales are considered final once the service has been rendered or the digital product has been downloaded.
          </p>

          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">2. Eligible Refund Conditions</h2>
          <p className="leading-relaxed">We may offer a full or partial refund under the following exceptional circumstances:</p>
          <ul className="list-disc pl-5 mb-6 space-y-2 leading-relaxed">
            <li><strong>Technical Issues:</strong> If you experience severe technical issues preventing you from accessing or downloading your generated documents, and our support team is unable to resolve the issue within a reasonable timeframe.</li>
            <li><strong>Billing Errors:</strong> In the event of a clear billing error or duplicate charge on our end.</li>
          </ul>

          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">3. Non-Refundable Conditions</h2>
          <p className="leading-relaxed">Refunds will <strong>not</strong> be provided under the following circumstances:</p>
          <ul className="list-disc pl-5 mb-6 space-y-2 leading-relaxed">
            <li>Dissatisfaction with the formatting, phrasing, or content generated by the AI (you are expected to review and edit the output).</li>
            <li>Change of mind after a successful purchase and generation.</li>
            <li>Lack of usage of a subscription plan.</li>
          </ul>

          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">4. Requesting a Refund</h2>
          <p className="leading-relaxed">
            To request a refund under the eligible conditions, please contact our support team at <strong>support@abcv.com</strong> within 7 days of your purchase. Please include your order details, account email, and a detailed explanation of the issue.
          </p>
          <p className="leading-relaxed">
            We will review your request and notify you of the approval or rejection of your refund. If approved, the refund will be processed and applied to your original method of payment within a certain amount of days.
          </p>
        </div>
      </div>
    </div>
  );
}
